// Publish a generated file tree to a fresh GitHub repo — the "it ends somewhere
// you own" step. Once this returns a clone URL, the existing deploy spine takes
// over unchanged (create project -> deploy -> clone at SHA -> build -> run).
//
// Uses the GitHub REST + Git Data API directly over fetch; no Octokit dep. The
// token needs repo-create + contents scope (a classic PAT with `repo`, or a
// fine-grained token with Administration:write + Contents:write). This is a
// broader scope than the deploy pipeline's clone-only token — the builder is
// what actually creates repos.

import type { GeneratedFile } from "./generate.js";

const GH = "https://api.github.com";

export interface PublishInput {
  name: string; // repo name (already slugified)
  files: GeneratedFile[];
  description?: string;
  private?: boolean; // default true — the user's app is theirs to make public
  token?: string; // defaults to GITHUB_TOKEN
  owner?: string; // org to create under; defaults to the token's own user
  branch?: string; // default "main"
}

export interface PublishResult {
  repoUrl: string; // https clone URL — what deploy.projects.repo_url wants
  htmlUrl: string; // browser URL
  owner: string;
  repo: string;
  branch: string;
  sha: string; // the initial commit SHA
}

async function gh<T>(
  token: string,
  path: string,
  init?: RequestInit,
): Promise<T> {
  const res = await fetch(`${GH}${path}`, {
    ...init,
    headers: {
      authorization: `Bearer ${token}`,
      accept: "application/vnd.github+json",
      "x-github-api-version": "2022-11-28",
      "content-type": "application/json",
      "user-agent": "llama-apps-builder",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`github ${init?.method ?? "GET"} ${path} → ${res.status}${detail ? `: ${detail}` : ""}`);
  }
  // 204s (rare here) have no body.
  return (res.status === 204 ? undefined : await res.json()) as T;
}

export async function publishToGithub(
  input: PublishInput,
): Promise<PublishResult> {
  const token = input.token ?? process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN is not set");
  if (!input.files.length) throw new Error("no files to publish");
  const branch = input.branch ?? "main";

  // 1. Create the repo (empty — we push the first commit ourselves so the tree
  //    is exactly the generated files, no auto-init README to fight with).
  const createPath = input.owner ? `/orgs/${input.owner}/repos` : "/user/repos";
  const repo = await gh<{ name: string; owner: { login: string }; clone_url: string; html_url: string }>(
    token,
    createPath,
    {
      method: "POST",
      body: JSON.stringify({
        name: input.name,
        description: input.description ?? "Generated by llama-apps builder",
        private: input.private ?? true,
        auto_init: false,
        has_issues: false,
        has_wiki: false,
        has_projects: false,
      }),
    },
  );
  const owner = repo.owner.login;
  const name = repo.name;
  const base = `/repos/${owner}/${name}`;

  // 2. Blob per file (base64 so binary-safe and newline-safe), then one tree.
  const tree = await Promise.all(
    input.files.map(async (f) => {
      const blob = await gh<{ sha: string }>(token, `${base}/git/blobs`, {
        method: "POST",
        body: JSON.stringify({
          content: Buffer.from(f.contents, "utf8").toString("base64"),
          encoding: "base64",
        }),
      });
      return { path: f.path, mode: "100644", type: "blob", sha: blob.sha };
    }),
  );
  const treeObj = await gh<{ sha: string }>(token, `${base}/git/trees`, {
    method: "POST",
    body: JSON.stringify({ tree }),
  });

  // 3. Root commit (no parents), then point the branch ref at it.
  const commit = await gh<{ sha: string }>(token, `${base}/git/commits`, {
    method: "POST",
    body: JSON.stringify({
      message: "Initial generation — llama-apps builder",
      tree: treeObj.sha,
    }),
  });
  await gh(token, `${base}/git/refs`, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: commit.sha }),
  });

  return {
    repoUrl: repo.clone_url,
    htmlUrl: repo.html_url,
    owner,
    repo: name,
    branch,
    sha: commit.sha,
  };
}
